"use client";

import MangeJobsList from "@/components/dashboard/job/manage-jobs-list";
import Layout from "@/components/dashboard/layout";
import useUser, { UserGoBack, UserNotLogin } from "@/lib/auth/user";
import Head from "next/head";
import React from "react";

export default function ManagesJobs() {
  const { user, loggedIn, loggedOut, isCandidate } = useUser();
  const userData = user;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {isCandidate && <UserGoBack />}
          {userData && loggedIn && !isCandidate && <MangeJobsList />}
        </main>
      </Layout>
    </>
  );
}
