import Layout from "@/components/Layout/Layout";
import AllCompanies from "@/components/dashboard/companies/all-companies";
import useUser, { UserGoBack, UserNotLogin } from "@/components/lib/user";
import Head from "next/head";
import React from "react";

export default function ManagesCompanies() {
  const { user, loggedIn, loggedOut, isCandidate } = useUser();
  const userData = user;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {isCandidate && <UserGoBack />}
          {userData && loggedIn && !isCandidate && <AllCompanies />}
        </main>
      </Layout>
    </>
  );
}
