"use client";

import CategoryInfo from "@/components/dashboard/job-alerts/category-info";
import Layout from "@/components/dashboard/layout";
import useUser, { UserGoBack, UserNotLogin } from "@/lib/auth/user";
import Head from "next/head";
import React from "react";

export default function Category() {
  const { user, loggedIn, loggedOut, isAdmin } = useUser();
  const userData = user;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {userData && !isAdmin && <UserGoBack />}
          {userData && loggedIn && isAdmin && <CategoryInfo />}
        </main>
      </Layout>
    </>
  );
}
