"use client";

import Layout from "@/components/Layout/Layout";
import PageTitle from "@/components/page-title";
import Head from "next/head";
import React from "react";

export default function ContactUs() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <PageTitle title="Contact Us" />
          <section>
            <div className="container mx-auto px-3 sm:px-0 py-10 md:py-20">
              <div>
                <h1 className="text-4xl font-semibold text-[#373737]">
                  Reach Us Quickly
                </h1>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-full">
                  <div className="w-full mt-16">
                    <div className="border-l-4 border-rose-400 px-5">
                      <p className="text-lg font-medium text-[#373737]">
                        Address
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        158 Ralegih Sit, Houston, <br /> Yk 5896,UK
                      </p>
                    </div>

                    <hr className="my-7" />
                    <div className="border-l-4 border-blue-400 px-5">
                      <p className="text-lg font-medium text-[#373737]">
                        Phones
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        (406) 555-0120{" "}
                        <span className="text-themePrimary">(Toll Free)</span>
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        (406) 555-0120
                      </p>
                    </div>
                    <hr className="my-7" />
                    <div className="border-l-4 border-orange-400 px-5">
                      <p className="text-lg font-medium text-[#373737]">
                        E-Mail
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        Support87@Gmial.Com
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        Info@Youremial.Com
                      </p>
                    </div>
                  </div>
                </div>

                <div className="pt-10 w-full block">
                  <iframe
                    className="h-96"
                    src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12075.377291106915!2d-74.084481!3d40.831383!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x3e3160910d4d5045!2sHoliday%20Inn%20Express%20%26%20Suites%20Meadowlands%20Area%2C%20an%20IHG%20Hotel!5e0!3m2!1sen!2sbd!4v1648105833329!5m2!1sen!2sbd"
                    width="100%"
                    height="100%"
                    allowFullScreen
                    loading="lazy"
                  ></iframe>
                </div>
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
