"use client";

import Layout from "@/components/Layout/Layout";
import PageTitle from "@/components/page-title";
import Head from "next/head";
import React from "react";

export default function ContactUs() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <PageTitle title="Contact Us" />
          <section>
            <div className="container mx-auto px-3 sm:px-0 py-10 md:py-20">
              <div>
                <h1 className="text-4xl font-semibold text-[#373737]">
                  Reach Us Quickly
                </h1>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 w-full">
                  <div className="w-full mt-16">
                    <div className="border-l-4 border-rose-400 px-5">
                      <p className="text-lg font-medium text-[#373737]">
                        Address
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        District 7, Ho Chi Minh City, <br /> Viet Nam
                      </p>
                    </div>

                    <hr className="my-7" />
                    <div className="border-l-4 border-blue-400 px-5">
                      <p className="text-lg font-medium text-[#373737]">
                        Phones
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        (406) 555-0120{" "}
                        <span className="text-themePrimary">(Toll Free)</span>
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        (406) 555-0120
                      </p>
                    </div>
                    <hr className="my-7" />
                    <div className="border-l-4 border-orange-400 px-5">
                      <p className="text-lg font-medium text-[#373737]">
                        E-Mail
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        support87@tdtu.edu.vn
                      </p>
                      <p className="text-grayLight text-base font-normal pt-2">
                        Info@tdtu.edu.vn
                      </p>
                    </div>
                  </div>
                </div>

                <div className="pt-10 w-full block">
                  <iframe
                    className="h-96"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3920.0239008087274!2d106.69718361111012!3d10.732639889369368!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528b2747a81a3%3A0x33c1813055acb613!2zxJDhuqFpIGjhu41jIFTDtG4gxJDhu6ljIFRo4bqvbmc!5e0!3m2!1svi!2s!4v1711103069588!5m2!1svi!2s"
                    width="100%"
                    height="100%"
                    allowFullScreen
                    loading="lazy"
                  ></iframe>
                </div>
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
