"use client";

import Layout from "@/components/dashboard/layout";
import AllResumes from "@/components/dashboard/manage-resumes/all-resumes";
import useUser, { UserGoBack, UserNotLogin } from "@/lib/auth/user";
import Head from "next/head";

export default function ManagesResumes() {
  const { user, loggedIn, loggedOut, isEmployer } = useUser();
  const userData = user;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {isEmployer && <UserGoBack />}
          {userData && loggedIn && !isEmployer && <AllResumes />}
        </main>
      </Layout>
    </>
  );
}
