"use client";

import AllApplications from "@/components/dashboard/job/all-applied-job";
import Layout from "@/components/dashboard/layout";
import useUser, { UserGoBack, UserNotLogin } from "@/lib/auth/user";
import Head from "next/head";
import React from "react";

const Applications = () => {
  const { user, loggedIn, loggedOut, isEmployer } = useUser();
  const userData = user;
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {userData && loggedIn && <AllApplications />}
        </main>
      </Layout>
    </>
  );
};

export default Applications;
