"use client";

import Layout from "@/components/Layout/Layout";
import { Loader } from "@/lib/loader/loader";
import useUser, { UserLogin } from "@/lib/auth/user";
import LoginForm from "@/components/register/login-form";
import Head from "next/head";
import React from "react";

const Login = () => {
  const { loggedOut, loggedIn } = useUser();

  if (loggedOut) {
    return (
      <>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <Layout>
          <main>
            <section className="py-24 md:py-32 bg-light">
              <LoginForm />
            </section>
          </main>
        </Layout>
      </>
    );
  }

  if (loggedIn) return <UserLogin />;
  return <Loader />;
};

export default Login;
