import Layout from "@/components/Layout/Layout";
import useUser, { UserGoBack, UserNotLogin } from "@/components/lib/user";
import Head from "next/head";
import React from "react";

export default function AddResume() {
  const { user, loggedIn, loggedOut, isEmployer } = useUser();
  const userData = user;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {isEmployer && <UserGoBack />}
          {/* {userData && loggedIn && !isEmployer && <EditResume />} */}
        </main>
      </Layout>
    </>
  );
}
