"use client";

import Layout from "@/components/Layout/Layout";
import ProfileBox from "@/components/dashboard/profile";
import useUser, { UserNotLogin } from "@/lib/auth/user";
import { users } from "@/utils/dummy-content/mongodb-collections/Untitled";
import Head from "next/head";
import React from "react";

const MyProfile = () => {
  const { user, loggedIn, loggedOut } = useUser();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {user && loggedIn && <ProfileBox currentUser={user} />}
        </main>
      </Layout>
    </>
  );
};

export default MyProfile;
