import BlogItem from "@/components/Blogs/BlogItem";
import Layout from "@/components/Layout/Layout";
import PageTitle from "@/components/page-title";
import { blogsData } from "@/data/blogData";
import _ from "lodash";
import Head from "next/head";
import React from "react";

export default function CareerAdvice() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <PageTitle title="Career Advice" />
          <section className="py-16 md:py-20 lg:py-24 bg-white">
            <div className="container">
              <div className="grid gap-4 xl:gap-6 xl:grid-cols-3 md:grid-cols-2">
                {_.map(blogsData, (item, index) => (
                  <BlogItem data={item} key={index} />
                ))}
              </div>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
