"use client";

import AddCategoryForm from "@/components/dashboard/form/add-category-form";
import Layout from "@/components/dashboard/layout";
import useUser, { UserGoBack, UserNotLogin } from "@/lib/auth/user";
import Head from "next/head";
import React from "react";

const AddCategory = () => {
  const { user, loggedIn, loggedOut, isAdmin } = useUser();
  const userData = user;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {userData && !isAdmin && <UserGoBack />}
          {userData && loggedIn && <AddCategoryForm />}
        </main>
      </Layout>
    </>
  );
};

export default AddCategory;
