import Layout from "@/components/Layout/Layout";
import PageTitle from "@/components/page-title";
import Head from "next/head";
import React from "react";

const PageNotFound = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <PageTitle title="Page Not Found" />
        </main>
      </Layout>
    </>
  );
};

export default PageNotFound;
