"use client";

import Layout from "@/components/Layout/Layout";
import CategorySection from "@/components/categories/category-section";
import PageTitle from "@/components/page-title";
import { ThemeContext } from "@/context/ThemeContext";
import { LoaderGrowing } from "@/lib/loader/loader";
import Head from "next/head";
import React from "react";

export default function AllCategory() {
  const { categoryData, categoryError } = React.useContext(ThemeContext) as any;
  console.log("categoryData: ", categoryData);
  if (categoryError) return <div>Error! {categoryError.message}</div>;
  if (!categoryData) return <LoaderGrowing />;

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <PageTitle title="All Categories" />
          <section className="pt-20 pb-24 !bg-light">
            <div className="container">
              <CategorySection categoryData={categoryData} />
            </div>
          </section>
        </main>
      </Layout>
    </div>
  );
}
