import Layout from "@/components/Layout/Layout";
import PageTitle from "@/components/page-title";
import { resumes } from "@/data/mongodb collections/resumes";
import Head from "next/head";
import { usePathname } from "next/navigation";

// const fetcher = (url: string) => Axios(url).then((res) => res.data);

export default function CandidateProfile() {
  const pathName = usePathname();
  const id = pathName.split("/").at(-1);
  const data = resumes;
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          <PageTitle title="Candidate Profile" />
          {/* {error && (
            <div className="h-40 text-center shadow rounded-lg bg-white w-full">
              failed to load
            </div>
          )} */}
          {/* <CandidateInfo data={data} /> */}
        </main>
      </Layout>
    </>
  );
}
