"use client";

import AllList from "@/components/dashboard/bookmarks/all-list";
import Layout from "@/components/dashboard/layout";
import useUser, { UserNotLogin } from "@/lib/auth/user";
import Head from "next/head";
import React from "react";

export default function Bookmarks() {
  const { user, loggedIn, loggedOut } = useUser();
  const userData = user;

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <main>
          {loggedOut && <UserNotLogin />}
          {userData && loggedIn && <AllList />}
        </main>
      </Layout>
    </>
  );
}
